Algoritmo "somador-numerico"
//  
//  
// Somador numerico
// Esse programa irá fazer solicitar 5 números, e cada vez que for solicitado
// ele guardará na memória e somara com o numero seguinte..
Var
cont,n : inteiro
s: inteiro


Inicio

cont <- 1
s <- 0
enquanto (cont <=5)faca
escreval ("Digite um número para realizarmos a soma..")
leia(n)
cont <- (cont +1)
s <- (s + n)





fimenquanto
escreval ("o valor da soma é : ", s)

Fimalgoritmo